version: '3.1'

# When spun up, run:
# docker exec -it zioriteofpassage-db-1 psql -U docker
# \c demodb;
# select * from jobs;
services:
  db:
    image: postgres
    restart: always
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
    environment:
      - "POSTGRES_USER=docker"
      - "POSTGRES_PASSWORD=docker"
    ports:
      - "5432:5432"